version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
  db:
    image: postgres:14.0
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
